<?php

namespace Carteleria\CarteleriaBundle\Entity;

/**
 * PlanEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
