<?php

namespace Carteleria\CarteleriaBundle\Entity;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * PlanRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRoomRepository extends \Doctrine\ORM\EntityRepository
{

    public function Rooms($inicio,$fin,$tipos){
       $em=$this->getEntityManager();
       $query ="select * from plan_room r join plan_entry e on r.id = e.room_id where e.type in('". implode("','", $tipos). "') and e.start_time >=".$inicio." and e.start_time <=".$fin.' order by e.start_time';
         $stmt = $em->getConnection()->prepare($query);
         $stmt->execute();
        return $stmt->fetchAll();
//        print(count($result).' rows');
//        print('<br>');
//
//        foreach($result as $data){
//            print_r($data['room_id']);
//            print('<br>');
//        }
//
//        die();
//
//
//
//       // print("E.type  in ('".implode(',', $tipos)."')'");die();
//        $qb = new QueryBuilder($this->getEntityManager());
//        $qb
//            ->select("R","E")
//            ->from($this->getClassName(), "R")
//            ->join('R.entries', "E")
//            ->where("E.type  in ('".implode("','", $tipos)."')")
//            ->andWhere('E.start_time >='.$inicio)
//            ->andWhere('E.start_time <='.$fin)
//        ;
//
//   //   print($qb->getQuery()->getDQL());
//
//        return $qb->getQuery()->getResult();
    }
}
